[build]
  publish = "."
  command = "echo Netlify build: static shell only; all routes proxied to backend"

[[redirects]]
# Proxy ALL routes to the ASP.NET Core backend (replace the URL below)
  from = "/*"
  to = "https://REPLACE_WITH_BACKEND_HOST/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src 'self' data: https:;"
